// The CostSauce purchase entry form — Task 12's real Add tab content,
// replacing Task 9's placeholder. Every write here goes through
// `LocalEdits` (ingredient creation, purchase creation); this screen never
// touches `LocalStore`'s write surface directly and never opens a network
// connection itself -- offline is the point (§11): matching, ingredient
// creation, and purchase creation are all local-store operations, and the
// only thing that ever reaches the network is the debounced
// `appModel.syncSoon()` call after a successful save.
//
// Global Constraints: money/qty values are STRINGS end to end -- `qty`,
// `unit`, `qtyInCase`, `totalPrice` are passed through to
// `LocalEdits.createPurchase` exactly as typed. `qty_base_units` is never
// computed in this file: `createPurchase` (via `Kernel.normalizePurchase`)
// is the sole owner of that derivation, and the post-save "success
// indicator" reads it back from the row `createPurchase` just wrote rather
// than re-deriving it here. `purchased_on` is never touched by
// Date/Calendar arithmetic -- the `DatePicker`'s own `Date` is only ever
// read via `Kernel.todayLocalISO(now:)` (the same "read local Y/M/D
// components" call the default value itself uses), never added to or
// subtracted from.

import SwiftUI
import CostSauceKit

struct PurchaseEntryView: View {
    let appModel: AppModel

    /// The currently picked ingredient, reported by `IngredientPickerView`'s
    /// `onPick` -- the extracted component owns the search/match/create-new
    /// state (Task 7); this is the one thing this screen needs back from it.
    @State private var selectedIngredient: LocalIngredient?
    /// Regenerated by `resetFormKeepingDate()` and applied to
    /// `IngredientPickerView` via `.id(_:)` -- forces SwiftUI to tear down
    /// and recreate the picker after a save, which resets ITS private
    /// search-query/selection state the same way `resetFormKeepingDate()`
    /// used to reset `nameQuery`/`manualSelection` directly before the
    /// picker was extracted into its own view.
    @State private var pickerResetToken = UUID()

    // Purchase fields.
    @State private var purchaseDate = Date()
    @State private var qty = ""
    @State private var unit = ""
    @State private var qtyInCase = ""
    @State private var totalPrice = ""

    @State private var errorMessage: String?
    @State private var savedMessage: String?

    var body: some View {
        Form {
            if let savedMessage {
                // Deliberately OUTSIDE the ingredient-gated section below --
                // `resetFormKeepingDate()` clears the selection right after
                // a save, which would otherwise carry this banner away with
                // it before the user ever saw it.
                Section {
                    Label(savedMessage, systemImage: "checkmark.circle.fill")
                        .foregroundStyle(.green)
                }
            }
            IngredientPickerView(appModel: appModel, excludedIngredientIds: [], onPick: pick)
                .id(pickerResetToken)
            if let selectedIngredient {
                purchaseDetailsSection(for: selectedIngredient)
            } else {
                Section {
                    Text("Search for an ingredient above, or create a new one, to continue.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
            }
        }
        .onChange(of: unit) { _, newUnit in
            if newUnit != "case" {
                qtyInCase = ""
            }
        }
    }

    /// `IngredientPickerView`'s `onPick` -- replaces the old
    /// `.onChange(of: effectiveSelectionId)` handler (same default-unit /
    /// `qtyInCase`-reset side effect), plus clearing a lingering "Saved"
    /// banner now that the user has picked a new ingredient for the next
    /// purchase.
    private func pick(_ ingredient: LocalIngredient) {
        selectedIngredient = ingredient
        unit = unitChoices(for: ingredient).first ?? ""
        qtyInCase = ""
        savedMessage = nil
    }

    private func unitChoices(for ingredient: LocalIngredient) -> [String] {
        appModel.edits?.unitChoices(baseUnit: ingredient.base_unit) ?? []
    }

    // MARK: - Purchase fields

    @ViewBuilder
    private func purchaseDetailsSection(for ingredient: LocalIngredient) -> some View {
        Section("Purchase") {
            DatePicker("Date", selection: $purchaseDate, displayedComponents: .date)
            TextField("Quantity", text: $qty)
                .keyboardType(.decimalPad)
            Picker("Unit", selection: $unit) {
                ForEach(unitChoices(for: ingredient), id: \.self) { choice in
                    Text(choice).tag(choice)
                }
            }
            if unit == "case" {
                TextField("Quantity per case", text: $qtyInCase)
                    .keyboardType(.decimalPad)
            }
            TextField("Total price", text: $totalPrice)
                .keyboardType(.decimalPad)
        }
        if let errorMessage {
            Section {
                Text(errorMessage).foregroundStyle(.red)
            }
        }
        Section {
            Button("Save Purchase") {
                save()
            }
            .disabled(!canSave)
        }
    }

    private var canSave: Bool {
        selectedIngredient != nil && !qty.isEmpty && !unit.isEmpty && !totalPrice.isEmpty
            && (unit != "case" || !qtyInCase.isEmpty)
    }

    /// `Kernel.todayLocalISO(now:)` reading the `DatePicker`'s own `Date` --
    /// the one sanctioned "read local Y/M/D components" use (same call the
    /// default `purchaseDate = Date()` resolves through), never
    /// `DateFormatter`/`Calendar` add-subtract arithmetic.
    private var purchasedOn: String {
        Kernel.todayLocalISO(now: purchaseDate)
    }

    /// Save → `createPurchase` → success indicator (`Kernel.unitPrice` read
    /// back from the row `createPurchase` just wrote, never re-derived from
    /// the raw form fields) → `syncSoon()` → form resets keeping the date.
    private func save() {
        guard let edits = appModel.edits, let ingredient = selectedIngredient else { return }
        errorMessage = nil
        savedMessage = nil
        do {
            let id = try edits.createPurchase(
                ingredientId: ingredient.id, purchasedOn: purchasedOn, qty: qty, unit: unit,
                qtyInCase: unit == "case" ? qtyInCase : nil, totalPrice: totalPrice)
            savedMessage = successMessage(purchaseId: id, ingredient: ingredient)
            appModel.syncSoon()
            resetFormKeepingDate()
        } catch let error as KernelError {
            errorMessage = error.message
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private func successMessage(purchaseId: String, ingredient: LocalIngredient) -> String {
        guard let store = appModel.store,
            let purchase = try? store.livePurchases(ingredientId: ingredient.id)
                .first(where: { $0.id == purchaseId }),
            let unitPrice = try? Kernel.unitPrice(
                totalPrice: purchase.total_price, qtyBaseUnits: purchase.qty_base_units)
        else {
            return "Purchase saved."
        }
        return "Saved — $\(unitPrice)/\(ingredient.base_unit)"
    }

    private func resetFormKeepingDate() {
        selectedIngredient = nil
        pickerResetToken = UUID()
        qty = ""
        unit = ""
        qtyInCase = ""
        totalPrice = ""
    }
}
